<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-08-24T20:27:04 IST" name="PetSuite" finished-at="2025-08-24T20:27:11 IST" duration-ms="6859">
    <groups>
    </groups>
    <test started-at="2025-08-24T20:27:04 IST" name="PetTest" finished-at="2025-08-24T20:27:11 IST" duration-ms="6859">
      <class name="api.test.Club">
        <test-method is-config="true" signature="setupData()[pri:0, instance:api.test.Club@2756c0a7]" started-at="2025-08-24T20:27:04 IST" name="setupData" finished-at="2025-08-24T20:27:04 IST" duration-ms="57" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupData -->
        <test-method signature="testSendOTP()[pri:1, instance:api.test.Club@2756c0a7]" started-at="2025-08-24T20:27:04 IST" name="testSendOTP" finished-at="2025-08-24T20:27:09 IST" duration-ms="5194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSendOTP -->
        <test-method signature="verifyOTP()[pri:2, instance:api.test.Club@2756c0a7]" started-at="2025-08-24T20:27:09 IST" name="verifyOTP" finished-at="2025-08-24T20:27:10 IST" duration-ms="710" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyOTP -->
        <test-method signature="testClubCategories()[pri:3, instance:api.test.Club@2756c0a7]" started-at="2025-08-24T20:27:10 IST" name="testClubCategories" finished-at="2025-08-24T20:27:10 IST" duration-ms="304" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testClubCategories -->
        <test-method signature="testGetLiveClubs()[pri:4, instance:api.test.Club@2756c0a7]" started-at="2025-08-24T20:27:10 IST" name="testGetLiveClubs" finished-at="2025-08-24T20:27:11 IST" duration-ms="227" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [204]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [204]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at org.testng.Assert.assertEquals(Assert.java:1274)
at api.test.Club.testGetLiveClubs(Club.java:116)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetLiveClubs -->
      </class> <!-- api.test.Club -->
    </test> <!-- PetTest -->
  </suite> <!-- PetSuite -->
</testng-results>
